import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "leaflet/dist/leaflet.css";
import PoliceHeader from "@/components/PoliceHeader";
import PoliceSidebar from "@/components/PoliceSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PoliceHeader />
        <div className="bg-[#0b1220] text-white/90 min-h-[calc(100dvh-56px)]">
          <div className="max-w-6xl mx-auto flex">
            <PoliceSidebar />
            <main className="flex-1 px-4 py-6">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
